const getFakedName = () => {
  const FAKED_NAMES = [
    'Melanie Davidson',
    'Donna Ferguson',
    'Donna Russell',
    'Nicola Duncan',
    'Jasmine Burgess',
    'Theresa Payne',
    'Nicola Lewis',
    'Phil Vaughan',
    'Stephen McDonald',
    'Wendy Rutherford',
    'Lisa Parr',
    'Charles Davies',
    'Max Davies',
    'Robert Walker',
    'Dan Wilson',
    'Cameron Fisher',
    'Kylie Wilson',
    'Steven Randall',
    'Carl Murray',
    'Samantha Hudson',
    'Dominic Metcalfe',
    'Anthony Robertson',
    'Kimberly Walsh',
    'Harry Campbell',
    'Gavin Bailey',
    'Una Greene',
    'Megan Fisher',
    'Rose Stewart',
    'Jane Powell',
    'Jessica Lambert',
    'Una Russell',
    'Joe Ince',
    'Penelope Kerr',
    'Cameron Metcalfe',
    'Sean Cameron',
    'James Baker',
    'Ruth Turner',
    'Stewart Simpson',
    'Keith Murray',
    'Jonathan Smith',
    'Jane Jones',
    'Megan Bell',
    'Dan Forsyth',
    'Simon Bell',
    'Adrian Randall',
    'Tracey Turner',
    'Benjamin Piper',
    'Virginia Slater',
    'Victoria Harris',
    'Penelope Chapman',
    'Jan Morrison',
    'Frank Hardacre',
    'Ella Paterson',
    'Victor Hart',
    'Warren Bond',
    'Christopher Pullman',
    'Yvonne Blake',
    'Julian Nash',
    'Madeleine Morgan',
    'Sally Abraham',
    'Ryan Lee',
    'Diana Turner',
    'Anne Watson',
    'Christopher Hughes',
    'Blake Parr',
    'Leah Churchill',
    'Diana Morrison',
    'Jason Martin',
    'Eric Powell',
    'Virginia Baker',
    'Deirdre Dyer',
    'Rose Paterson',
    'Angela Paige',
    'Ava Sanderson',
    'Ella Lambert',
    'Charles Carr',
    'Joanne Hill',
    'Sue Harris',
    'Jonathan Allan',
    'Deirdre Avery',
    'Joe Piper',
    'Simon Marshall',
    'Tim Vance',
    'Andrew Glover',
    'Lisa Burgess',
    'Tracey Welch',
    'William Cameron',
    'Peter Slater',
    'Benjamin Baker',
    'David Paige',
    'William Ellison',
    'Stephanie Dickens',
    'Thomas Blake',
    'James Grant',
    'Blake Mitchell',
    'Audrey Berry',
    'Julia Wilson',
    'Anna Knox',
    'Hannah Miller',
    'Lily Ince'
  ]

  return FAKED_NAMES[(Math.floor(Math.random() * FAKED_NAMES.length) + 1) - 1]
}

const getFakedPost = () => {
  const FAKED_POSTS = [
    'I want take a Beer, and this is awesome',
    'Who playing today? Chicago Rebels?',
    'Some times I want simple things: ride motorcycle and cigara!',
    'So... what we gonna do?! This is Havai baby!',
    'Nah... wont be a one of bad guys. Want be a Superman!',
    'Being in a situation that looks to be hopeless!',
    'Getting sincere about something; applying oneself seriously to a job.',
    'One who may seem plain at first in appearance or capability, but later turns out to be beautiful or great.',
    'To keep going, pressing forward; never stopping.',
    'What you would expect to happen; something normal or common.',
    'Mike is good. But somtimes tired and lazzy! This is just a job side effect :)',
    'To risk it all, even if it means losing everything. To go all out.',
    'Being faced with two difficult choices.',
    'Delicious; something that looks or tastes appetizing.',
    'Coming close to a successful outcome only to fall short at the end.',
    'Nonviolent; someone who is mild or gentle.',
    'It\'s better to teach a person how to do something than to do that something for them.',
    'Something that is all over.',
    'To ruin someone\'s happy moment.',
    'Keeping calm. Usually said by someone who is trying to avoid making others upset.',
    'Being in a dangerous or very deadly situation.',
    'Angry; being roused to the point that you are ready to fight.',
    'Something that is extremely expensive.',
    'One who may seem plain at first in appearance or capability, but later turns out to be beautiful or great.',
    'It\'s better to teach a person how to do something than to do that something for them.',
    'A shout of agreement, or to draw attention to a speaker.',
    'Performing an action with the greatest of haste.',
    'Being angry about something that happened in the past.',
    'Failing to recall a memory. Unable to remember something.',
    'People tend to associate with others who share similar interests or values.'
  ]

  return FAKED_POSTS[(Math.floor(Math.random() * FAKED_POSTS.length) + 1) - 1]
}

module.exports = {
  getFakedName: getFakedName,
  getFakedPost: getFakedPost
}
